### PR TITLE
Add info about tox to FAQ section

### PR DESCRIPTION
**Pull request by tadeoos**
This PR adds info about using tox with Poetry as discussed in #222.

There is no contributing guide so I am not sure if this should be merged to `master` or `develop` branch, but since other PRs are merging into master, I followed their lead.

### CODE REVIEW

**Comment by tadeoos** [comment]
@sdispater I want to make sure that the info in FAQ is actually enough: I wonder if tox will be able to execute the `poetry` commands in venvs since it is not being installed anywhere explicitly...

**Comment by sdispater** [comment]
As long as you have `poetry` installed on your system, you should be fine. That's why we have to specify `whitelist_externals = poetry` to tell `tox` to execute the `poetry` executable located outside the tox virtualenv.

**Comment by tadeoos** [comment]
Great, thanks!

**Comment by sdispater** [comment]
Looks good to me. Thanks!

**Pull request merged**
