### PR TITLE
Check to ensure the global config exists before reading

### PR DESCRIPTION
**Pull request by Caligatio**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

---

#1272 introduced a bug on "develop" where poetry performs a blind read on the global config file without checking whether it exists first.  This is a one-line fix that simply checks to make sure the file exists before the read.  The existing follow-on code already handles creation of the file just fine.

This should close out #1179

### CODE REVIEW

**Comment by Caligatio** [comment]
I'm pretty sure Travis CI just hiccuped during my tests as those failures have absolutely nothing to do with the changed code.

**Comment by brycedrennan** [comment]
@Caligatio thanks for this fix. 

The same test is failing in 4 different python versions so I don’t think it’s a hiccup: ‘test_list_displays_default_value_if_not_set’

**Comment by Caligatio** [comment]
Pinned down the problem: this is a brittle unit test that made strong assumptions on how a file would be tested whether it exists.  My original code was correct but I edited it to make it fit the mock assumptions.  I don't know why/how but my code was previously passing (locally) on Win10 Python 3.7 **without** the modification in place (weird).

P.S. - My last commit message should have been "by using exists" and not "by existing exists."  It's getting late :(

**Comment by brycedrennan** [comment]
Great thank you!

**Pull request merged**
