### PR TITLE
Enhancement: add flag to show package version

### PR DESCRIPTION
**Pull request by bradsbrown**
# Description

This PR adds a `-s|--show` flag to `poetry version` that will print out the current package version and exit. This is useful both for manual checks and for automation as a way to easily access the version info without having to parse the `pyproject.toml` file within user code.

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ✅ ] Added **tests** for changed code.
- [ ✅  ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by zymergen-jonas** [comment]
This is similar to https://github.com/sdispater/poetry/issues/629. Note that in the issue you have to scroll down until you see consensus that emerge in https://github.com/sdispater/poetry/issues/629#issuecomment-440048020:

> @mattyclarkson, @abn - great, sounds like we're all on the same page: keep poetry version but make it display the current project's current version, and add something to explicitly do a third point increment.
> 
> @sdispater - would you welcome a PR that made this happen?

**Comment by jonemo** [comment]
This is similar to https://github.com/sdispater/poetry/issues/629. Note that in the issue you have to scroll down until you see consensus that emerge in https://github.com/sdispater/poetry/issues/629#issuecomment-440048020:

> @mattyclarkson, @abn - great, sounds like we're all on the same page: keep poetry version but make it display the current project's current version, and add something to explicitly do a third point increment.
> 
> @sdispater - would you welcome a PR that made this happen?

**Comment by mbello** [comment]
I agree with this suggestion. Also, maybe poetry version --quiet should output only the new version instead of nothing. But still we will need a way to get the package version without at the same time increasing the version number.

**Comment by sdispater** [comment]
Closing this. I think we can implement it the way suggested in #629

**Pull request closed without merging**
