### PR TITLE
[Documentation] Added instructions for Oh-My-Zsh completion

### PR DESCRIPTION
**Pull request by declared-lambda**
# Pull Request Check List

- [ ] Added **tests** for changed code.  
N/A
- [ ] Updated **documentation** for changed code.
N/A

### CODE REVIEW

**Comment by sdispater** [comment]
Thanks for taking the time to make this PR!

However, unless I am missing something, won't the instructions for `zsh` also work on `oh-my-zsh`?

**Comment by declared-lambda** [comment]
They do work but it's not clear as neither `compinit` nor fpath are in `~/.zshrc`.  


For `oh-my-zsh` to load _poetry, `fpath+=~/.zfunc` needs to be put before `oh-my-zsh`'s 
`plugins(...)` call.

The other solution to this, is the one I proposed in the PR, where completions are exported in `oh-my-zsh`'s plugins folder and is loaded by adding poetry in `plugins( ... )` call.


I initially opened a PR in `oh-my-zsh` that added `poetry`'s completions in the plugins folder but was rejected and the proposed solution in the reply is not working at all.  
https://github.com/robbyrussell/oh-my-zsh/pull/7132  

I can revert it back and add a note for `oh-my-zsh` to insert `fpath+=~/.zfunc` before `plugins(...)` if that'd be better.

**Comment by levi-rs** [comment]
I found out about Poetry from [this HN post](http://andrewsforge.com/article/python-new-package-landscape/), and wanted to give it a try. I couldn't get the zsh completion instructions to work, as @declared-lambda outlined, as I use oh-my-zsh. I followed the PR changes and they worked perfectly.

**Comment by webknjaz** [comment]
This PR is good. I'd only suggest adding an omz plugin to the upstream repo as it's a true way to introducing such integration.

**Comment by sdispater** [comment]
Thanks!

**Comment by MisLink** [comment]
How about outputting to `$ZSH/custom/plugins`? `$ZSH/plugins` is under git and means accepted by oh-my-zsh maintainers.

**Pull request merged**
