### PR TITLE
Resolve git refs to git revisions [#1331]

### PR DESCRIPTION
**Pull request by bibz**
# Pull Request Check List

- [X] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Fixes bug #1331.

### CODE REVIEW

**Comment by bibz** [comment]
Since this is a bugfix, the submission is on `master`.
The equivalent change exists for `develop` too (see bibz/poetry@d57e4c49ad7ab97fe241742237af281a93107279).

**Comment by bibz** [comment]
Oops I got bit by Python 2 and `**dict`.

OK so now I've ran `tox` and made sure Python 2.7, 3.5, and 3.6 worked. I cannot install Python 3.4 easily, but it should not be a problem :crossed_fingers: .

**Comment by stephsamson** [comment]
Hey @bibz thanks for your contribution! 🍡 💫 

Can you resolve the conflict? The bug fix for master looks good to me so this would be good to merge once the conflicts are resolved.

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
