### PR TITLE
Make `publish` command retrive username and password from environment variables.

### PR DESCRIPTION
**Pull request by moigagoo**

### CODE REVIEW

**Comment by moigagoo** [comment]
The tests fail, but it seems to have nothing to do with the PR. Current `develop` fails as well.

**Comment by sdispater** [comment]
Thanks for you PR.

However, I find the envvars names to generic. Maybe `POETRY_PUBLISH_USERNAME` and `POETRY_PUBLISH_PASSWORD`?

**Comment by sdispater** [comment]
@moigagoo Yes. We can settle for the options for now and only merge #72 and close this one.

**Comment by moigagoo** [comment]
@sdispater Could you please review and merge #73 (if it's OK) so that we could close this one?

**Comment by pawamoy** [comment]
So, was it merged? I would really like to avoid typing my username and password each time I publish.

**Pull request closed without merging**
