### PR TITLE
Change README default format to Markdown and add it to pyproject.toml automatically

### LINKED ISSUE #280: Default README format to Markdown in "new"?
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
When Markdown support was initially added in https://github.com/sdispater/poetry/issues/15, Warehouse had somewhat questionable Markdown rendering. At this point, however, it appears that those issues have been resolved, and things like syntax highlighting now work.

As such, given the relative popularity of Markdown even for Python projects, it might make more sense for `new` to default to creating a `README.md` rather than a `README.rst`.

### PR DESCRIPTION
**Pull request by cauebs**
- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

Closes #280.

The problem right now is that I cannot change the `pyproject.toml`'s structure, which is created here: https://github.com/cauebs/poetry/blob/a8b534811c1e11541673eb426d34ef9b824321d4/poetry/layouts/layout.py#L84-L89

I don't find the current solution very elegant. If I want to optionally add the readme to the default pyproject.toml, we'll end up with four different strings (with license and readme, just readme, just license or neither). I could edit the strings to insert a line in the correct position, but that's ugly as well. This TOML library is becoming very inconvenient. How should I deal with this?

### CODE REVIEW

**Comment by sdispater** [comment]
Just so you know I am currently developing a TOML library which should ease the programmatic creation/modification of the `pyproject.toml` file.

I'll let you know when it's ready (hopefully it should be this week).

**Comment by cauebs** [comment]
Awesome. Let me know if you want some help ;)

**Comment by sdispater** [comment]
@cauebs I merged the PR with the new TOML library ([TOML Kit](https://github.com/sdispater/tomlkit)) which should help with interacting with the `pyproject.toml` file.

**Comment by finswimmer** [comment]
Close in favor of https://github.com/sdispater/poetry/pull/1515

**Pull request closed without merging**
