### PR TITLE
Use authentication credentials in install, search commands (#233)

### PR DESCRIPTION
**Pull request by Gr1N**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by Gr1N** [comment]
@sdispater please review, if you're okay with proposal then I will go to write tests.

**Comment by cauebs** [comment]
Don't forget to run the [black formatter](https://github.com/ambv/black) on your code ;)

**Comment by Gr1N** [comment]
@cauebs this is very strange because on my local black said that everything is ok. Will try to investigate.

**Comment by Gr1N** [comment]
Can't understand what is wrong:
```
Projects/Python/poetry on auth-creds
➜ poetry show | ack black
black                  18.6b4    The uncompromising code formatter.

Projects/Python/poetry on auth-creds
➜ poetry run black .
All done! ✨ 🍰 ✨
262 files left unchanged.
```

**Comment by ojii** [comment]
> Can't understand what is wrong:

If you set up [pre-commit](https://pre-commit.com/) it will auto-format on commit (poetry is set up for pre-commit already). To run it on all files, you can `pre-commit run --all-files`. 

The problem is likely a black version mismatch which would be solved by this.

**Comment by Gr1N** [comment]
I've fixed Python 2.7 compatibility issues and build passed, very strange :)

**Comment by Gr1N** [comment]
So what about fix, is it okay?

**Comment by Gr1N** [comment]
Closing in prior of #306

**Pull request closed without merging**
