### PR TITLE
Add `--username` and `--password` options to `publish` command.

### PR DESCRIPTION
**Pull request by moigagoo**

### CODE REVIEW

**Comment by sdispater** [comment]
Thanks! Looks good to me!

Could you rebase your PR to resolve the current conflict in the `CHANGELOG.md` file?

**Comment by moigagoo** [comment]
@sdispater Please check if I've done everything correctly with the conflict. Thanks!

**Comment by sdispater** [comment]
@moigagoo You still need to rebase like you did in #74

**Comment by moigagoo** [comment]
@sdispater Sorry, I gave up and opened a new PR: https://github.com/sdispater/poetry/pull/83

**Pull request closed without merging**
