### PR TITLE
Update version strings in project files. (#144)

### PR DESCRIPTION
**Pull request by JnyJny**
#144 

Added a dry-run option to version command and logic to
replace current version strings with next version in:
- pyproject.toml
- python source ( assignments & comparisons )
- markdown | restructured text | plain text

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [X] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

### CODE REVIEW

**Comment by JnyJny** [comment]
I took a stab at writing tests for this new feature, but ran into trouble due to lack of familiarity with how to use/extend the fixtures already provided. I'll keep working the problem.

**Comment by tarkatronic** [comment]
This is an interesting approach, but I could see a lot of potential for false positives, in places like a changelog, or even list of requirements. What if you require a specific version of a package, which matches the version of your local package?

I think a better approach might be explicit configuration of the locations of the version, such as how `bumpversion` works. The alternative would be expecting the user to perform a dry run before *every* version bump, which as a user, is simply not going to happen.

**Comment by JnyJny** [comment]
> This is an interesting approach, but I could see a lot of potential for false positives, in places like a changelog, or even list of requirements. What if you require a specific version of a package, which matches the version of your local package?

Excellent point that I had not considered. 

> I think a better approach might be explicit configuration of the locations of the version, such as how `bumpversion` works. The alternative would be expecting the user to perform a dry run before _every_ version bump, which as a user, is simply not going to happen.

Excellent feedback, thank you. I'm not sure how opinionated poetry wants to be about how a package is structured so my goal was to avoid specifying where version data should go.

**Comment by funkyfuture** [comment]
i think this functionality is out of `poetry`'s scope. but it might be fitting a coming plugin ecosystem.

**Comment by JnyJny** [comment]
@funkyfuture I disagree, poetry already changes the project version number in pyproject.toml, it's a small step forward to take the burden off the developer and change it in the shipping (code/docs) part of the project.

**Comment by sdispater** [comment]
Thanks for you contribution!

However, this is beyond the intended purpose of `version` which is to update the version in the `pyproject.toml` which is the only file under the control of Poetry.

I am closing this but that's a feature that can be implemented as a plugin when they are supported.

**Pull request closed without merging**
