### PR TITLE
Add support for url dependencies

### PR DESCRIPTION
**Pull request by sdispater**
## Pull Request Check List

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

This PR adds support for URL dependencies.

Adding a URL dependency to the current project can be done in two ways: via the `add` command or by modifying the `pyproject.toml` file directly.

```bash
poetry add https://example.com/packages/my-package-1.0.0.tar.gz
```

```toml
[tool.poetry.dependencies]
my-package = {url = "https://example.com/packages/my-package-1.0.0.tar.gz"}
```

### CODE REVIEW

**Comment by marctorrellas** [comment]
I tried to install spacy language model like this


```
(title_detector) MacBook-MacBook-Pro-de-Marc:title_detector marctorrellassocastro$ poetry add https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz

Updating dependencies
Resolving dependencies... (6.6s)


Package operations: 1 install, 0 updates, 0 removals

  - Installing en_core_web_sm (2.1.0 https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz)

[EnvCommandError]
Command ['/Users/marctorrellassocastro/Library/Caches/pypoetry/virtualenvs/title-detector-uYNvqQ-e-py3.7/bin/python', '-m', 'pip', 'install', '--no-deps', 'en-core-web-sm==2.1.0'] errored with the following return code 1, and output:
Collecting en-core-web-sm==2.1.0
  Could not find a version that satisfies the requirement en-core-web-sm==2.1.0 (from versions: )
No matching distribution found for en-core-web-sm==2.1.0
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

but didn't work. Doing `pip install <url>` it works. Am I doing something wrong?

**Comment by im-n1** [comment]
Just tried this and doesnt work on tar/zip balls.

```
{ url = "https://github.com/im-n1/django-seed/archive/bf8b56d.zip" }
```

doesn't work because of 
```
[SolverProblemError]
Because middleware depends on django-seed (*) which doesn't exist, version solving failed.
```

**Comment by Jamim** [comment]
Hello @im-n1,
> Just tried this and doesnt work on tar/zip balls.

Could you please submit an issue?
Thank you!

**Comment by im-n1** [comment]
I just did. Feel free to do your internal issue management. Bye.

**Comment by AdamGold** [comment]
Any news on this?

**Comment by PranitModak** [comment]
Hi @sdispater ,
Can you please let me know the format in which we would have to mention this.

I have tried the following in pyproject.toml
 ```toml
[tool.poetry.dependencies.tensorflow]
version = "~2.3"
url = "https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.3.2.tar.gz"
 ```

got this error

 ```error
  The Poetry configuration is invalid:
    - [dependencies.tensorflow] {'version': '~2.3', 'url': 'https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.3.2.tar.gz'} is not valid under any of the given schemas
 ```

when I tried this:

```toml
[tool.poetry.dependencies]
tensorflow= { url = "https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.3.2.tar.gz" }
 ```

got this error

 ```error
  TypeError

  expected string or bytes-like object

  at ~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/utils/helpers.py:27 in canonicalize_name
       23│ _canonicalize_regex = re.compile(r"[-_]+")
       24│ 
       25│ 
       26│ def canonicalize_name(name):  # type: (str) -> str
    →  27│     return _canonicalize_regex.sub("-", name).lower()
       28│ 
       29│ 
       30│ def module_name(name):  # type: (str) -> str
       31│     return canonicalize_name(name).replace(".", "_").replace("-", "_")
 ```  

> ## Pull Request Check List
> * [x]  Added **tests** for changed code.
> * [x]  Updated **documentation** for changed code.
> 
> This PR adds support for URL dependencies.
> 
> Adding a URL dependency to the current project can be done in two ways: via the `add` command or by modifying the `pyproject.toml` file directly.
> 
> ```shell
> poetry add https://example.com/packages/my-package-1.0.0.tar.gz
> ```
> 
> ```toml
> [tool.poetry.dependencies]
> my-package = {url = "https://example.com/packages/my-package-1.0.0.tar.gz"}
> ```

**Comment by ashnair1** [comment]
I got the same error as @PranitModak  (`TypeError: expected string or bytes-like object`). Is there a fix for this?

**Pull request merged**
