### PR TITLE
allow to read package version from specified variable

### LINKED ISSUE #144: peotry version doesn't bump the value in __version__
$ poetry version 0.1.1
    Bumping version from 0.1.0 to 0.1.1
    $ grep version pyproject.toml 
    version = "0.1.1"
    $ grep version */__init__.py
    src/__init__.py:__version__ = '0.1.0'
    $ poetry --version
    Poetry 0.9.0

I don't know if it's intended or not. A way to do that safely is to parse the root `__init__.py`, detect `__version__`, back it up, extract the ast, bump the version string and replace it, then extract the new ast and compare the result. If both ast are the same, except for the version, the file semantics have been preserved. Otherwise, rollback the change and display an error message stating we can't bump the version safely.

### PR DESCRIPTION
**Pull request by vanyakosmos**
- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

There is a problem when you need to specify version of the package twice: in `pyproject.toml` and in `package.__version__`. We can't read `pyproject.toml` to calculate `__version__` because config file is not available to the final user of package.

I propose to add alternative definition of version where you need to specify path to the variable which will hold the value of package version.

```toml
[tool.poetry]
version = { attr = "package.sub_module:__version__" }
```
for project with structure:
```
my-package
        ├── pyproject.toml
        ├── README.rst
        └── package
            ├── __init__.py
            └── sub_module.py  # has __version__ variable

```

this pull request should close #144

### CODE REVIEW

**Comment by vanyakosmos** [comment]
isort failed on "setup.py" files despite `[tool.isort] skip_glob = ["*/setup.py"]` in `pyproject.toml` 🤔

**Comment by finswimmer** [comment]
I've contacted @sdispater as I has the same problem with the `isort` test. It works now.

**Comment by ryanhiebert** [comment]
Hi @vanyakosmos , I was watching this pull request, and it looks like you closed it without resolution. Is there some other issue that conflicts or otherwise relates to this one?

**Comment by vanyakosmos** [comment]
"Double source of package version" problem is controversial (so controversial that some doesn't even see it as problem). Related issue has been opened for over a year and resolution is not yet in sight. 
As for now this pull request just wastes space in PRs lists. So I decided to close PR and wait for some conclusions and thoughts from Sebastien regarding this issue.

**Pull request closed without merging**
