### PR TITLE
add pipx as installation method #677

### PR DESCRIPTION
**Pull request by cs01**
pipx is a new project similar to pipsi, but with more features and actively maintained

### CODE REVIEW

**Comment by bersace** [comment]
Hi @cs01. The commit subject is misleading. It's about **replacing** pipsi with pipx.

Also, pipx is registered for another project on PyPI : https://pypi.org/project/pipx/

Welcome to pip*hell* ;-)

**Comment by bersace** [comment]
Anyway, your pipx looks nice !

**Comment by cs01** [comment]
> pipx is registered for another project on PyPI

I'm aware. We've had a lot of discussion about this in https://github.com/cs01/pipx/issues/2. This pipx can be installed from PyPI with pipx-app.

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
