### PR TITLE
Resolve specified extras of poetry directory dependencies (#282)

### PR DESCRIPTION
**Pull request by RaptDept**
* Copy poetry package extras to directory dependency
* Exclude unspecified extras during version resolution
* Add tests in test_installer

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by sdispater** [comment]
Thanks for taking the time to make this PR!

One thing: we should make a separate test and not update the existing one. That way we can see if the test failing comes from the `extras` feature or is a generic problem with directory dependencies.

**Comment by RaptDept** [comment]
I'm not sure what you mean by not updating the existing one. The existing test `test_run_installs_with_local_directory` was renamed to `test_run_installs_with_local_setuptools_directory` but otherwise remains untouched. The new test for this PR is `test_run_installs_with_local_poetry_directory_with_extras`, and it uses new fixtures (with `pyproject.toml` instead of `setup.py`).

Do you mean I should make a test that checks `extras` resolution for every dependency type instead?

**Comment by sdispater** [comment]
@RaptDept Oh, sorry I misread the PR!

Looks good to me then!

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
