### PR TITLE
Add support for special characters in username/password for pip

### PR DESCRIPTION
**Pull request by Caligatio**
# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

----

Per #1249 and [pip #6776](pip/issues#6775), newer versions of pip require require the username and password to be properly encoded/quoted.  This PR simply `quote`s the URL when calling pip.

As referenced in #1249, we do not want to pre-quote the strings as that fouls up the metadata fetch which does not use pip.

### CODE REVIEW

**Comment by stephsamson** [comment]
Does this bug also exist on master? If so, then this PR should be merged into master and not into develop.

**Comment by oleastre** [comment]
See my comment on #1402 , the fix should be applied to `master` branch as well, but the code changed between the two versions and this patch can not be applied as is to `master`

**Comment by Caligatio** [comment]
As @oleastre mentioned, there is a significant code divergence between `master` and `develop` so the patch cannot be applied to `master`. My recommendation is to not let perfect be the enemy of good and just merge both #1402 and this PR.

Honestly, this `master` vs `develop` situation is a giant pain and, as highlighted by this situation, is impeding work. It's only getting worse since there was a major refactor in `develop` that changes many core functions.

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
