### PR TITLE
Support POETRY_HOME for install

### LINKED ISSUE #775: Support customizable POETRY_HOME
It would be nice to define where poetry gets installed (via get-poetry.py).

By reading the docstring I had assumed it would work in $POETRY_HOME, but that was quickly disproven.

Ideally this could be defined via an environment variable (POETRY_HOME) or via a flag to get-poetry.py.

### PR DESCRIPTION
**Pull request by dcramer**
Allow the `POETRY_HOME` environment variable to be passed during installation to change the default installation directory of `~/.poetry`:

```
POETRY_HOME=/etc/poetry python get-poetry.py
```

Fixes #775

### CODE REVIEW

**Comment by dcramer** [comment]
Didn't look like there were any good existing test hooks for this but lmk if that's a concern. I did a manual QA and it appeared to work as expected.

**Comment by JoshuaRLi** [comment]
@dcramer Oh nice, does this mean Sentry is going to be moving over to the new `pyproject.toml` PEP and along with that, potentially `poetry` and `black`? Well, I'm going to close https://github.com/getsentry/sentry/pull/9026 anyways, I don't like nor use `pipenv` personally anymore.

**Comment by dcramer** [comment]
@JoshuaRLi migrated https://github.com/getsentry/zeus and some of my personal projects - not sure what we'll do for sentry core yet

**Comment by dvf** [comment]
This is a welcome change. This is the last piece of the puzzle for us to ditch Pipenv for Poetry.

**Comment by EvanPurkhiser** [comment]
Is there anything blocking this? Right now https://github.com/sdispater/poetry/issues/775#issuecomment-480039875 works well.

**Comment by Peque** [comment]
@sdispater Friendly ping for the second-most-upvoted MR. :innocent:

**Comment by stephsamson** [comment]
Thanks for the PR @dcramer 🍡 💫 
This looks good to me -- can you fix the conflict before I merge this?

**Comment by dcramer** [comment]
I'll leave it in someone elses court. Wont have time this week or next, and dont have a devenv setup for it right now. I imagine it's pretty easy if someone wants to tackle it.

**Comment by stephsamson** [comment]
@dcramer okay, thanks! I'll pick this up myself next week then.

Thanks again for your contribution 🙌

**Comment by glass-ships** [comment]
sorry to comment on a long since merged PR but I wasn't sure where to leave this...
is this feature supported in Windows as well? the documentation didn't provide a CMD example so it didn't seem immediately clear

**Comment by neersighted** [comment]
Yes, the same environment variables are supported on Windows.

**Pull request merged**
