### PR TITLE
Allow uploading of wheels with local version identifier

### PR DESCRIPTION
**Pull request by hoefling**
This is a follow-up of #950 that allows publishing of wheels with local version identifier. Many thanks in advance for reviewing!

- [x] ~~Added **tests** for changed code.~~ Extended existing ones instead of adding dupes.
- [ ] ~~Updated **documentation** for changed code.~~ Same reason as in #950.

### CODE REVIEW

**Comment by kbakk** [comment]
Good catch. I wasn't using the upload functionality, so I missed it. Seeing how I missed it, it could happen again in the future. Perhaps create a static function on WheelBuilder, which handles filename? And use this in both places (poetry/masonry/builders/wheel.py and poetry/masonry/publishing/uploader.py).

**Comment by hoefling** [comment]
@kbakk I guess this went unnoticed because both `re.sub`s in `WheelBuilder` and `Uploader` are code dupes, so refactoring them is indeed a good solution, but I'm unsure where to place the code. Are you suggesting a method in `WheelBuilder` and import it in the `Uploader`? Or maybe add another pair of functions like `escape_name`/`escape_version` to `poetry.utils.helpers`? Or maybe `escaped_name`/`escaped_version` properties to `poetry.packages.package.Package`?

```python
class Package(object):
    ...
    @property
    def escaped_name(self):
        return re.sub(r"[^\w\d.]+", "_", self.pretty_name, flags=re.UNICODE)
```

I'm not sure where to place both `re.sub`s, so any decision is welcome from my side.

**Comment by kbakk** [comment]
All seems to be viable options. In addition, there's `poetry.masonry.utils.helpers`.

**Comment by hoefling** [comment]
@kbakk great suggestion, I like that! Added the necessary changes.

**Comment by hoefling** [comment]
@sdispater sure thing, done!

**Comment by sdispater** [comment]
Thanks!

**Pull request merged**
