### PR TITLE
Leave '+' alone in dist-info and wheel names

### PR DESCRIPTION
**Pull request by dimbleby**
Else local build versions such as 1.2.3+company.1 are installed as
1.2.3_company.1, which is interpreted by pip as 1.2.3-company.1

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by brycedrennan** [comment]
Thanks for your contribution. I'll leave the evaluation of the merits of this change to someone else.  

Two asks:

- Since this changes current behavior could you please make this a pull request into the `develop` branch?
- Could you add some test cases?

**Comment by dimbleby** [comment]
> Since this changes current behavior could you please make this a pull request into the develop branch?

I definitely view this as a bug fix.  Packages with local version identifiers are currently mis-built so that they install with the wrong version number, which results in bogus version conflicts.

(It's true that this also changes behaviour; but all bug fixes change behaviour - else they wouldn't fix anything...)

> Could you add some test cases?

Maybe!  Can you please point me at an existing test case that I can copy and tweak?

**Comment by brycedrennan** [comment]
I've reclassified this as a bug.

For reference: https://legacy.python.org/dev/peps/pep-0440/#local-version-identifiers

You should add a new test [in this file](https://github.com/sdispater/poetry/blob/dd44419881773b5465281827622985b53bbf8fff/tests/semver/test_version.py#L1)
[Here is a list of perhaps relevant versions to test.](https://github.com/sdispater/poetry/blob/dd44419881773b5465281827622985b53bbf8fff/tests/semver/test_version.py#L9)

Thanks!

**Comment by dimbleby** [comment]
> You should add a new test in this file

This was bad advice, tests in that file go nowhere near the changed code.  But I figured it out.

**Comment by brycedrennan** [comment]
Whoops yep copied the same link twice.  Thanks for adding a test. I’ll take a look.

**Comment by brycedrennan** [comment]
Just noticed that #950 is addressing the same thing

**Comment by dimbleby** [comment]
This one goes further in that it also retains the `+` in the dist-info path - which I believe is required else, per opening comment, pip sees the underscore and normalizes it to a `-`.

So I'd ask that you prefer this one to that.

(Obviously we all are busy and open source maintainers have my gratitude and sympathy... but isn't this frustrating!  It would be lovely if y'all were able to handle relatively straightforward pull requests like this on a faster cycle - so that we users could benefit from them, rather than having to re-discover them).

**Comment by kbakk** [comment]
> This one goes further in that it also retains the + in the dist-info path - which I believe is required else, per opening comment, pip sees the underscore and normalizes it to a -.

That is a nice catch, which indeed should be included. Though, seeing that this implements the exact changes and tests as I had, with exception of two lines, I feel that it could be rebased upon my PR branch, retaining my commit.

**Comment by dimbleby** [comment]
>  I feel that it could be rebased upon my PR branch, retaining my commit.

Sure, whatever!  If I had known about the existing PR, I wouldn't have re-written it...

(If it's important to you that your commit be included, I've no problem with you updating it so that it includes the second fix, and we abandon this one.)

**Comment by kbakk** [comment]
I've now included the change with dist-info (added you @dimbleby as co-author, hope that's fine). I suggest to close this, and continue in #950, hopefully it can be merged shortly.

**Comment by brycedrennan** [comment]
The combined fix has now been merged. Thanks!

**Pull request closed without merging**
