### PR TITLE
Add a Code of Conduct

### PR DESCRIPTION
**Pull request by danyeaw**
Adds a code of conduct to the project :heart: 

# Pull Request Check List

This is just a reminder about the most common mistakes. Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://poetry.eustace.io/docs/contributing/) at least once, it will save you unnecessary review cycles!

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

**Note**: If your Pull Request introduces a new feature or changes the current behavior, it should be based
on the `develop` branch. If it's a bug fix or only a documentation update, it should be based on the `master` branch.

If you have *any* questions to *any* of the points above, just **submit and ask**!  This checklist is here to *help* you, not to deter you from contributing!

### CODE REVIEW

**Comment by danyeaw** [comment]
Why are people down voting a Code of Conduct?

**Comment by Serkan-devel** [comment]
Here's a better one:

# Contributor Code of Conduct

This project adheres to No Code of Conduct.  We are all adults.  We accept anyone's contributions.  Nothing else matters.

**Comment by Peque** [comment]
@Serkan-devel Do you think, based on your (probably-not-too-vast) experience contributing to big free-software projects, you can come up with a better code of conduct than the ones that have been adopted by big projects and organizations like:

- [Linux](https://github.com/torvalds/linux/blob/master/Documentation/process/code-of-conduct.rst)
- [Python Software Foundation](https://www.python.org/psf/codeofconduct/)
- [Vue.js](https://github.com/vuejs/vue/blob/dev/.github/CODE_OF_CONDUCT.md)
- [Tensorflow](https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md)
- [Facebook](https://code.fb.com/codeofconduct/)
- [Microsoft](https://opensource.microsoft.com/codeofconduct/)

Can you share links to (preferably well-known) projects or organizations that adhere to a code of conduct similar to the one you are proposing?

**Comment by Ryuno-Ki** [comment]
Ah, since you are referencing Linux CoC here … have you read [the critics on its introduction](https://itsfoss.com/linux-code-of-conduct/)?

**Comment by danyeaw** [comment]
I guess why I found it surprising that people gave this is a thumbs down, is that to me, the Python community is the most openly accepting and diverse group in tech. The PSF and PyCon both have and rigorously enforce a Code of Conduct to make sure that the community is welcoming and comfortable for everyone to contribute to.

**Comment by Ryuno-Ki** [comment]
Open and welcome does not mean, that one can't argue (to find a balanced solution), does it? :-)

Maybe it's worth for those voting to explain their motivation. Above you already asked.

**Comment by stephsamson** [comment]
@danyeaw thanks for your contribution. I do think that a code of conduct is past due, not just because other projects are doing it but because everyone who *wants* to contributes to Poetry should neither feel intimidated nor unwelcome.

@Ryuno-Ki A code of conduct does not discourage people from arguing but rather it establishes a baseline for constructive arguments. For example, usage of the ad hominem fallacy often derails the conversation at hand and discourages people from participating. Not only that, but it lowers the quality of the discussion. It is a very basic guideline in any modern open source project.

**Comment by Jamim** [comment]
Hello @danyeaw,

> Why are people down voting a Code of Conduct?

I guess it's because people don't like being forced to be kinder than they already are.

**Pull request merged**
